'''Класс параметров пользовательского интерфейса'''

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_encryption(object):
    def setupUi(self, encryption):
        encryption.setObjectName("encryption")
        encryption.resize(1183, 788)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(encryption.sizePolicy().hasHeightForWidth())
        encryption.setSizePolicy(sizePolicy)
        encryption.setMinimumSize(QtCore.QSize(971, 677))
        encryption.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(encryption)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.message = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message.sizePolicy().hasHeightForWidth())
        self.message.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.message.setFont(font)
        self.message.setObjectName("message")
        self.horizontalLayout_2.addWidget(self.message)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.language = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language.sizePolicy().hasHeightForWidth())
        self.language.setSizePolicy(sizePolicy)
        self.language.setMinimumSize(QtCore.QSize(254, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.language.setFont(font)
        self.language.setObjectName("language")
        self.language.addItem("")
        self.language.addItem("")
        self.verticalLayout.addWidget(self.language)
        self.name_chipher = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_chipher.sizePolicy().hasHeightForWidth())
        self.name_chipher.setSizePolicy(sizePolicy)
        self.name_chipher.setMinimumSize(QtCore.QSize(254, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_chipher.setFont(font)
        self.name_chipher.setObjectName("name_chipher")
        self.name_chipher.addItem("")
        self.name_chipher.addItem("")
        self.verticalLayout.addWidget(self.name_chipher)
        self.procedure = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.procedure.sizePolicy().hasHeightForWidth())
        self.procedure.setSizePolicy(sizePolicy)
        self.procedure.setMinimumSize(QtCore.QSize(254, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.procedure.setFont(font)
        self.procedure.setObjectName("procedure")
        self.procedure.addItem("")
        self.procedure.addItem("")
        self.verticalLayout.addWidget(self.procedure)
        self.key = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key.sizePolicy().hasHeightForWidth())
        self.key.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.key.setFont(font)
        self.key.setObjectName("key")
        self.verticalLayout.addWidget(self.key)
        self.execute = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execute.sizePolicy().hasHeightForWidth())
        self.execute.setSizePolicy(sizePolicy)
        self.execute.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.execute.setFont(font)
        self.execute.setObjectName("execute")
        self.verticalLayout.addWidget(self.execute)
        self.verticalLayout.setStretch(0, 2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 7)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.return_message = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.return_message.setFont(font)
        self.return_message.setObjectName("return_message")
        self.verticalLayout_2.addWidget(self.return_message)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        encryption.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(encryption)
        self.toolBar.setObjectName("toolBar")
        encryption.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(encryption)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        encryption.setMenuBar(self.menubar)
        self.openFile = QtWidgets.QAction(encryption)
        self.openFile.setObjectName("openFile")
        self.openKey = QtWidgets.QAction(encryption)
        self.openKey.setObjectName("openKey")
        self.saveMessage = QtWidgets.QAction(encryption)
        self.saveMessage.setObjectName("saveMessage")
        self.saveEncryptMes = QtWidgets.QAction(encryption)
        self.saveEncryptMes.setObjectName("saveEncryptMes")
        self.saveKey = QtWidgets.QAction(encryption)
        self.saveKey.setObjectName("saveKey")
        self.menu.addAction(self.openFile)
        self.menu.addAction(self.openKey)
        self.menu.addAction(self.saveMessage)
        self.menu.addAction(self.saveEncryptMes)
        self.menu.addAction(self.saveKey)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(encryption)
        QtCore.QMetaObject.connectSlotsByName(encryption)

    def retranslateUi(self, encryption):
        _translate = QtCore.QCoreApplication.translate
        encryption.setWindowTitle(_translate("encryption", "Cryptographer"))
        self.message.setPlaceholderText(_translate("encryption", "Сообщение..."))
        self.language.setItemText(0, _translate("encryption", "Русский"))
        self.language.setItemText(1, _translate("encryption", "Анлийский"))
        self.name_chipher.setItemText(0, _translate("encryption", "Подстановочный шифр"))
        self.name_chipher.setItemText(1, _translate("encryption", "Шифр Виженера"))
        self.procedure.setItemText(0, _translate("encryption", "Зашифровать"))
        self.procedure.setItemText(1, _translate("encryption", "Расшифровать"))
        self.key.setPlaceholderText(_translate("encryption", "Ключ..."))
        self.execute.setText(_translate("encryption", "Выполнить"))
        self.return_message.setPlaceholderText(_translate("encryption", "Зашифрованное сообщение..."))
        self.toolBar.setWindowTitle(_translate("encryption", "toolBar"))
        self.menu.setTitle(_translate("encryption", "Файл"))
        self.openFile.setText(_translate("encryption", "Открыть редактируемый файл"))
        self.openKey.setText(_translate("encryption", "Открыть ключ"))
        self.saveMessage.setText(_translate("encryption", "Сохранить редактируемый файл"))
        self.saveEncryptMes.setText(_translate("encryption", "Сохранить результирующий файл"))
        self.saveKey.setText(_translate("encryption", "Сохранить ключ"))
