"""
Константы криптографической системы.
"""

CAST5_BLOCK_SIZE = 64
CAST5_IV_SIZE = 8

CAST5_MIN_KEY_SIZE = 40
CAST5_MAX_KEY_SIZE = 128
CAST5_KEY_STEP = 8

RSA_PUBLIC_EXPONENT = 65537
RSA_KEY_SIZE = 2048

DEFAULT_SETTINGS_PATH = "settings.json"

SHA256_ALGORITHM = "SHA256"
CAST5_ALGORITHM = "CAST5"
RSA_ALGORITHM = "RSA"